// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDttVgw_DgLsYghK7Wvdn_5lwaKL_Qj41k',
    appId: '1:570887500348:web:87e07631b727d5c97b0939',
    messagingSenderId: '570887500348',
    projectId: 'groupie-dart-project',
    authDomain: 'groupie-dart-project.firebaseapp.com',
    storageBucket: 'groupie-dart-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxGwJT7-kJGhGGJP32HXlo7qhhurHRpfs',
    appId: '1:570887500348:android:8dfc37264bafc54e7b0939',
    messagingSenderId: '570887500348',
    projectId: 'groupie-dart-project',
    storageBucket: 'groupie-dart-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAGrycbUjMnhVXJ_tvPYbrvRbGnMB2a2U',
    appId: '1:570887500348:ios:0e2b54ab1d3255357b0939',
    messagingSenderId: '570887500348',
    projectId: 'groupie-dart-project',
    storageBucket: 'groupie-dart-project.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAGrycbUjMnhVXJ_tvPYbrvRbGnMB2a2U',
    appId: '1:570887500348:ios:0e2b54ab1d3255357b0939',
    messagingSenderId: '570887500348',
    projectId: 'groupie-dart-project',
    storageBucket: 'groupie-dart-project.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
